### ISSUE TITLE
Augmented Database

### ISSUE THREAD

**Issue by sitongsu** [wchen342/SketchyGAN#10]
Hi,Dr chen:
i am a freshman in cv, it's my first work in this field. And i really appreciate you work in this paper
when i click the link of the augmented tfrecord dataset, it turns out to be "404 file not found". since the dataset was so large that i always failed in downloading it. so could you please upload a new download address or provide a new download method.
thanks a lot

**Comment by wchen342** [comment]
I apologize for the inconvenience. The website hosting my dataset (Onedrive Business) was linked to my college account and since I graduated it is no longer available. I haven't found any other website that will let me host 200G+ data for free, so I will suggest you fetch your own images by using the scripts I provided under `data_processing` folder.

**Comment by sitongsu** [comment]
thanks for your reply. i will try the crawler myself.

**Comment by YellowPig-zp** [comment]
Hi Dr.Chen, do you mind posting some instructions on the workflow for retrieving images and processing them? It would be a great help. Thanks!

**Comment by wchen342** [comment]
The basic workflow is like this: collect images from Flickr with `flickr_crawler.py` -> clear out unrelated images with `flickr_filter.py` -> edge detection with `batch_hed.py` -> post-processing with `PostprocessHED.m`.
